# .github/workflows/scheduled-calls.yml
name: Trigger notification call on a CRON Schedule

on:
  schedule:
    # Runs "everyday at 5:02pm" (see https://crontab.guru)
    - cron: '02 17 * * *'
  workflow_dispatch: {}

jobs:
  build:
    name: Trigger Notification Call
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: |
          curl -sS -X GET \
            -H "x-api-key: ${{ secrets.API_KEY }}" \
            "${{ secrets.BASE_URL }}/notify?email=${{ secrets.USER_EMAIL }}"
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Keepalive via workflow_dispatch
        uses: actions/github-script@v7
        env:
          REF: ${{ github.ref_name }}
        with:
          script: |
            const ref = process.env.REF || 'main';
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'scheduled-calls.yml',
              ref
            });
