# .github/workflows/scheduled-calls.yml
name: Trigger notification call on a CRON Schedule

on:
  schedule:
    # Runs "everyday at 5:02pm" (see https://crontab.guru)
    - cron: '02 17 * * *'
  workflow_dispatch: {}

jobs:
  build:
    name: Trigger Notification Call
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: |
          curl -sS -X GET \
            -H "x-api-key: ${{ secrets.API_KEY }}" \
            "${{ secrets.BASE_URL }}/notify?email=${{ secrets.USER_EMAIL }}"
      - uses: gautamkrishnar/keepalive-workflow@master # step to keep alive the cron action
